### ISSUE TITLE
[1.0.1] Prettify removes comments

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/graphql-playground#137]
Which is 'pretty', but not that 'pretty'. Please leave comments alone.

**Comment by timsuchanek** [comment]
The solution here would be to use "prettier". The problem there though is, that we need a custom build only including graphql. This is because otherwise it's multiple megabytes of code. Anyone who is interested in working on this can ping me in our slack @tim2.

**Comment by timsuchanek** [comment]
Thanks to https://github.com/prismagraphql/graphql-playground/pull/702 this is now solved 👏
