### ISSUE TITLE
Interface schema rendered with 'type' keyword

### ISSUE THREAD

**Issue by bdentino** [prismagraphql/graphql-playground#171]
Sorry to nitpick, but this is probably a trivial fix for someone familiar with the project. When the schema for an interface is rendered in its `doc-type-schema` div, it uses the `type` keyword instead of the `interface` keyword.

In the below screenshot, `Security` is defined as:

```
interface Security {
    ...
}
```
but the schema renders as:

![screen shot 2017-10-04 at 3 33 19 pm](https://user-images.githubusercontent.com/3820523/31202981-d6e73d76-a919-11e7-9bb7-36dbcf3cae49.png)

It would technically be more correct to show `interface` in this case, right? If I get some time to dig into the code base, I can take a stab at this myself unless someone beats me to it or informs me that my expected behavior here is misguided.

**Comment by timsuchanek** [comment]
Fixed by #568
