### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by lolcoolkat** [prismagraphql/graphql-playground#192]
I'll start off by just saying I was really looking forward to using the playground, for ease of use (using the web version of the playground can get quite tedious..so having this as a program would be so much easier), however it's turned out just to be so buggy I can't even stand to use it.

Here's a few bugs I've come across that are super frustrating.

1. **I try to start typing in the editor and all I get is this big grey block**

For some reason (prob the most frustrating part of the playground), is that I start a new tab and all I get is this grey block..and when I type nothing happens? I have to spam the keyboard and finally words will appear, and have to delete all the spam to start writing. Not sure if anyone else experiences this..but it's super annoying.

Example: https://gyazo.com/2688bde611e308362a67c463fa0ad78c (here i'm trying to start typing, but nothing happens)

2. **Sometimes the backspace button doesn't work**

Not sure what the deal is, but sometimes it works.. but other times you highlight a bit of text and the backspace button just doesn't do anything. Not sure if it has to do with specific rules or w/e but it's just super frustrating.

Example: https://gyazo.com/5662b00bbf56de58acff11eba912e53b

In this case I just want to switch the type quickly and it's super frustrating when editing is just a pain in the ass.

3. **Pressing return sometimes creates unwanted brackets**

This doesn't happen all the time.. but sometimes when pressing return...to add a new item to return from a query etc, it will add a new set of brackets...for reasons I have no idea. There seems to be a ton of unnecessary autocomplete in the editor, when there shouldn't be. 

4. **Editor seems to be over auto-completed**

I'm sure i'm using the wrong word here, but in my case.. the editor seems to be trying to do/add so much stuff I don't need or don't want to be doing. All I want is a simple code editor that I can edit and not have something be changed automatically for me, etc. I understand why it's done.. but it's just super frustrating when you know what you want to do, but the editor has a mind of it's own. Can there be an option for it to just be a simple code editor..with no autocomplete etc.. so we can just put our own code without it trying to be formated/changed/edited?

5. **Query variable editor is super buggy**

The autocomplete functionality in the query variable editor is overdone imo. When you click return for example.. simply wanting to go to the next line and add another variable, it adds for example a variable you have already defined, which is just stupid.

**Thoughts**

Please make the code editor, more hands off so users can do what they want to do, without everything being automatically generated/changed etc. Just like you would in the Atom editor or notepad++ etc. I understand; like I said before why it's there, but it's just become a pain in the ass. Please try and fix all the bugs to do with the editor..as I think the idea of a program for the playground is super amazing..but it's just too buggy to use atm.

Sorry for the fast/sloppy thoughts...but hopefully it makes sense ;)

And thanks to the Graph.Cool team for everything you have done so far..for the community <3

**Comment by timsuchanek** [comment]
Thanks for reporting @lolcoolkat !
Points 1 and 2 should be fixed by now.
Points 3 & 4 are fine-tuning settings, we could add a setting to make the autocompletion less obtrusive.
Point 5 is tracked here: https://github.com/prismagraphql/graphql-playground/issues/183

So the action item of this issues is: Add a setting to disable/minimize the auto-completion.
I created an issues to track 3 & 4: https://github.com/prismagraphql/graphql-playground/issues/708
