### ISSUE TITLE
Add Playground middleware to apollo-server

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#209]
We should create a PR to [apollo-server](https://github.com/apollographql/apollo-server) which adds built-in support for GraphQL Playground like this:

```ts
import express from 'express';
import bodyParser from 'body-parser';
import { graphqlExpress, playgroundExpress } from 'apollo-server-express';

const myGraphQLSchema = // ... define or import your schema here!
const PORT = 3000;

const app = express();

// bodyParser is needed just for POST.
app.use('/graphql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));
app.get('/playground', playgroundExpress({ endpointURL: '/graphql' })); // if you want GraphQL Playground enabled

app.listen(PORT);
```

**Comment by schickling** [comment]
- [ ] This is still blocked by #205 @timsuchanek

**Comment by kbrandwijk** [comment]
This would make it a lot heavier. Also, it would require separate packages for each server type first.

**Comment by morajabi** [comment]
@kbrandwijk 
> This would make it a lot heavier.

What do you mean? What will be heavier?

I can think of only two advantages of separating each middleware into a package now (like `graphql-playground-middleware-express`):
1. Releasing a new version for each without needing to bump the version up for all (e.g. when we introduce a breaking change for one, we need to bump only its version itself)
2. Less download for installing

**Comment by kbrandwijk** [comment]
I created https://github.com/graphcool/graphql-playground/issues/210 for that. I meant that the `apollo-server` package would become heavier by adding the additional dependencies needed for the playground.

**Comment by timsuchanek** [comment]
The latest apollo server ships the GraphQL Playground out of the box.
