### ISSUE TITLE
Request for hapi 17 support

### ISSUE THREAD

**Issue by cjihrig** [prismagraphql/graphql-playground#233]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
all

#### What version of graphql-playground(-electron) are you experience the issue(s) on?
`graphql-playground-middleware-hapi@1.x.x`

#### What is the expected behavior?
This is a request to support hapi 17.

#### What is the actual behavior?
The plugin crashes with hapi 17.

#### What steps may we take to reproduce the behavior?
Attempt to use this plugin with hapi 17 instead of hapi 16.

**Comment by timsuchanek** [comment]
@Saeris is working on this here https://github.com/graphcool/graphql-playground/pull/396
As soon as the PR is ready, we support hapi 17 :)

**Comment by timsuchanek** [comment]
The latest hapi middleware package supports hapi 17 🙂
