### ISSUE TITLE
playground middleware causes errors in aws lambda

### ISSUE THREAD

**Issue by sid88in** [prismagraphql/graphql-playground#278]
Reference: https://github.com/serverless/serverless-graphql-apollo/pull/192

<img width="1169" alt="screen shot 2017-11-27 at 8 25 33 pm" src="https://user-images.githubusercontent.com/1587005/33320875-8440a832-d3f8-11e7-8f25-42f5e5b3cd12.png">

**Comment by sid88in** [comment]
this issue got resolved.  next looking at : 

<img width="712" alt="screen shot 2017-12-01 at 9 48 36 am" src="https://user-images.githubusercontent.com/1587005/33495843-dddf6118-d67c-11e7-85bd-ae52a69265af.png">

**Comment by sid88in** [comment]
thanks a lot @timsuchanek for helping fixing these issues 🎉

**Comment by sid88in** [comment]
this issue only happens on local and not when deployed on aws

**Comment by sid88in** [comment]
also I see the metrics in tracing not on local but on aws!

**Comment by timsuchanek** [comment]
This is fixed in the latest lambda middleware.
