### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#291]
It should be possible to change the font size by pressing `CMD + +` and `CMD + -` or manually setting the value in the preferences. It should be stored as `editor.fontSize`.

**Comment by morajabi** [comment]
If by changing the font size you mean the whole UI font size, I think we need to have sizes in `rem` to do that.

**Comment by schickling** [comment]
I was just referring to the font size of the editors (query, variable, http header, response).

**Comment by Huvik** [comment]
Its now possible to change font size in config :)
