### ISSUE TITLE
Opening example database in Playground causes errors

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/graphql-playground#298]
#### This issue pertains to:

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground
- [ ] GraphQL Playground Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Win 10

#### What version of graphql-playground(-electron/-middleware) are you experience the issue(s) on?
1.3.0

#### What is the expected behavior?
It should just work.

#### What is the actual behavior?
When selecting the movie database on the start screen, the Playground opens with a 'failed to fetch' error, no schema, and no endpoint URL in the address bar. Running queries works however.

#### What steps may we take to reproduce the behavior?
Start playground. Select 'Movie Database'.
![image](https://user-images.githubusercontent.com/852069/33492604-d5916e02-d6bd-11e7-8afd-ce1931ae4af1.png)

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
