### ISSUE TITLE
Unable to load playground | Manually having to add endpoint to address bar in Console's Playground 

### ISSUE THREAD

**Issue by dukuo** [prismagraphql/graphql-playground#300]
![image](https://user-images.githubusercontent.com/347548/33496250-42009b96-d6a8-11e7-8fa2-4fc14790aec3.png)

- [ ] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10 64bits

#### What is the expected behavior?
Should add endpoint in the address bar next to the history button to run any query/mutation

#### What is the actual behavior?
Nothing is added into that field, and it looks like the whole functionality is derived from getting the value from there, so all the schema is disabled. 

#### What steps may we take to reproduce the behavior?
Upgrade npm package to latest version.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
