### ISSUE TITLE
Implement description on hover

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#315]
GraphiQL has introduced a couple of useful improvements over the last few months which should be merged back into the GraphQL Playground such as clicking on a field and opening it in the docs sidenav or tooltip descriptions when hovering a field in the query editor.

See [GraphiQL releases](https://github.com/graphql/graphiql/releases) for other features.

**Comment by timsuchanek** [comment]
The "click on field" has been implemented recently by @Huvik, the hover is still missing.

**Comment by Huvik** [comment]
I will add it to dynamic styles PR

**Comment by Huvik** [comment]
Hover is working in new version it just need some design adjustments
