### ISSUE TITLE
Subscription connectionParams in middleware-express

### ISSUE THREAD

**Issue by ZaninAndrea** [prismagraphql/graphql-playground#325]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground
- [x] GraphQL Playground Middleware

#### What version of graphql-playground(-electron/-middleware) are you experience the issue(s) on?
graphql-playground-middleware-express: 1.3.6

#### What is the expected behavior?
The subscription connection passes the right connectionParams

#### What is the actual behavior?
No connectionParams are passed

#### What steps may we take to reproduce the behavior?
Create a .graphqlconfig file like this:
```
{
    "schemaPath": "./graphql/types.graphql",
    "extensions": {
        "endpoints": {
            "dev": {
                "url": "http://localhost:3000/graphql",
                "headers": {
                    "Authorization":
                        "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTMzNDQ0NTMsInVzZXJJZCI6IjBkNGNkMmUzLTFmYzYtNGQ0Yy1iNGU1LTVkOWMwZTVhNzM3YiJ9.pzB60ipb1MasOe6--Eu3OsMPWhn0tTYL-rkBrD3rhWY"
                },
                "subscription": {
                    "url": "ws://localhost:3000/subscriptions",
                    "connectionParams": {
                        "Authorization":
                            "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTMzNDQ0NTMsInVzZXJJZCI6IjBkNGNkMmUzLTFmYzYtNGQ0Yy1iNGU1LTVkOWMwZTVhNzM3YiJ9.pzB60ipb1MasOe6--Eu3OsMPWhn0tTYL-rkBrD3rhWY"
                    }
                }
            }
        }
    }
}
```

And then use the package
```js
app.get(
    "/playground",
    expressPlayground({})
)
```

When opening the playground page the correct endpoints are chosen (so the .graphqlconfig file is read), but when connection the websocket, the server receives no connectionParams

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
