### ISSUE TITLE
Use prettier for "Prettify" feature

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#327]
[Prettier](https://github.com/prettier/prettier) is becoming the popular default when it comes to formatting code (including GraphQL queries). The "Prettify" button inside of the Playground should use prettier under the hood and should even be configurable in the setting.

**Comment by Huvik** [comment]
Sadly not possible, because prettier is unable to run in browser right now

**Comment by Glavin001** [comment]
Would a server based solution with an API work in this case? [Click here for the Unibeautify Playground](https://playground.unibeautify.com/#N4IgNghgdg5grhGBTAchAtkkAuEBxAJwgAcALARQBkQAaEAe2IBcBLeqAZx1AGEBibiABGSCHFYAzFkgJdsAbRAAFAkiZMAngAIAIiwkSQAXQC+dHgGULgkWMnTZORSrWbd+w3RfqHtEACkLAFoAIVFxfQ1jMxBLADUbcPsZOWdVdW09A2jzejAAEwAxOA42KES7fQdU5XS3LMNTOgBRQIqIqRSnWtdMjz9A0KTInPwiMip25McFHp8ZYzoIAgJ6AHcAfWJlpE4cEAgwNYgNLjp6IQArJABjJg2buAIwDQ2ObZuWWBwmAjgkOjEIgwdAQDZfDgyJg4CSHSF0S4cAAeGyERBuAGs1HJYWB4SA1uMNmAvkhibsYExSDgABwABkBwNBG1UAEc4CxVDC4QCQLt8hs1iwqW8kOgWDc8uxuXjeez6EwkHIQFB2Fg6F98rt7kKRUwIEI5L9-hqoFqoPdSgAvLDYAAspvN9xupGW+y0fn5guFpAe9HQoJlkJiAAkACoAWWo2FAtg61W63nq-TogzClQkUSaIHDUYA1M0AEohKZVLqzJN9bLZkPQfJgJBCZZyWPDTozNK9dzZVPBdMdLMxQIAeRQpfbNUr3c8c1YC17Qwzg97AA1xwmK3UqzOk74WhZKF9oQv+5JlwEIAA3CDr8udjLT0b+K8QCw3AgsZi3juz7d+XfziAzQHkeAx9m256UEqLbCG2G73smPazr42aHuyLD5N+NRphBowRssGL5Os5QxrBGbwchCzZhGJT6i6tqtuRd4BOBS6jIWbDQqRcbTJOW6PtmFiWNY3FwcxU4NP+dQoTEFhxHgWGJvxkmCRAHAwTxZY-hJ-SCR8jbNopm5dipslCjARkIX+2ZhsK0AsHA6BaBYmgNs5pBINilm-gJMRhuZ3k6dWfkaMQSBvh+X6iUx2nKSmlEEKMcQsBwCBgBI9AEDcDFkfG4lxcFdBxP8gXSVRMQrlGpUmfFOFsdmK5hmKxCQIq1UPqZMSZSwMBfIcTVIlxIDsjI2jAAAOlAWhaCUMgABQYdgWgAIwAJRaBNU3TVoUAYEgk3bVoiD7Vt00SB+-IcBtB2HTte03dNJg3U9UAmB6JhAA) which wraps [Prettier](prettier.io). Note in the network requests the query is sent to a public API hosted by RunKit ( https://runkit.com/glavin001/unibeautify-playground ).
