### ISSUE TITLE
First character overwritten in headers and variables tabs

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/graphql-playground#349]
When you start typing headers or variables, the first character you type is replaced by a `{`.
![brackets](https://user-images.githubusercontent.com/852069/34068410-4828bf2e-e23a-11e7-89e9-9df74b820536.gif)

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
