### ISSUE TITLE
Switching between workspaces resets tab state

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#353]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.3.9

https://youtu.be/nzt7qOTrxiA

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
