### ISSUE TITLE
Customize fontFamily and fontSize in config

### ISSUE THREAD

**Issue by blackxored** [prismagraphql/graphql-playground#355]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

Allow customizing fontFamily and size of editor in config editor.

**Comment by timsuchanek** [comment]
Implemented in latest version.
