### ISSUE TITLE
Slow with multiple tabs

### ISSUE THREAD

**Issue by blackxored** [prismagraphql/graphql-playground#356]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

If you open ~5 tabs or more the UI starts responding really slow and gets blocked for some time.

**Comment by marktani** [comment]
Thanks for the report, @blackxored! This could be one of the possible causes for #320.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
