### ISSUE TITLE
UI marks valid fragments as syntax errors

### ISSUE THREAD

**Issue by portenez** [prismagraphql/graphql-playground#371]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

Mac Ox High Sierra
#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Version 1.3.16 (1.3.16.137)

#### What is the expected behavior?
```Gherkin
When I input a query with valid Fragments
Then it is marked as valid gql query
```

#### What is the actual behavior?

```Gherkin
When I input a query with valid Fragments
Then it is marked it as an invalid gql query
```

#### What steps may we take to reproduce the behavior?

```Gherkin
Given I have a gql endpoint with a complex type
When I define a query with fragments of one of the subtypes
Then it is marked as invalid gql syntax
```

_Please provide a gif or image of the issue for a quicker response/fix._

```graphql
fragment characterFields on Character {
  name
}

query {
  character {
    ...characterFields
  }
}
```

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
