### ISSUE TITLE
Playground should open same workspaces after restarting or a full quit

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#382]
There's a difference between closing a window/workspace and completely closing the application via `CMD + Q`/restarting (e.g. via auto update).

In the case of completely closing & re-opening the application, the old session (= workspaces/windows) should be restored, in the case of manually closing a window/workspace nothing should be persisted (i.e. no need to re-open).

**Comment by timsuchanek** [comment]
We now persist every workspace and show the workspace overview again when you reopen it. This should solve this issue.
