### ISSUE TITLE
Make errors visible

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#385]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS X Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

Version 1.3.18 (1.3.18.201)

#### What is the expected behavior?

Errors should be shown in a prompt or otherwise easily visible.

#### What is the actual behavior?

Errors are only printed to the DevTools

#### What steps may we take to reproduce the behavior?

run `graphql playground` in a directory with an invalid `graphcool.yml` file.
The DevTools will show this error:

![image](https://user-images.githubusercontent.com/1780597/34539312-48521a00-f0d0-11e7-95a6-45d543c04f72.png)

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
