### ISSUE TITLE
Save results when switching workspaces

### ISSUE THREAD

**Issue by kbrandwijk** [prismagraphql/graphql-playground#387]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [X] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What is the expected behavior?
I would like to save the query output when switching workspaces. 

#### What is the actual behavior?
Now, the output is cleared when switching workspaces.

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
