### ISSUE TITLE
graphql playground doesn't open workspaces

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#390]
_From @marktani on January 3, 2018 19:26_

version: `1.3.18`

Instead, the default view is opened:

![image](https://user-images.githubusercontent.com/1780597/34536073-6a0113a6-f0c4-11e7-8fde-cae53d9a8e18.png)

### reproduction

```sh
git clone git@github.com:graphcool/graphcool-server-example.git
cd graphcool-server-example
graphcool deploy
yarn
graphql playground
```

_Copied from original issue: graphcool/graphcool-server-example#41_

**Comment by marktani** [comment]
_From @kbrandwijk on January 4, 2018 8:6_

@marktani  `yarn playground` just runs `graphql playground`. Can you move this issue to the `graphql-cli` repo?

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
