### ISSUE TITLE
Switching between projects breaks app when subscription running

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#463]
Playground version: Electron 1.3.22

Steps to reproduce:

- Clone https://github.com/graphcool/graphcool-server-example
- Start subscription in `app` project
- Open new tab in `database` project
- Trigger subscription (e.g. by creating a node)
- Switch back to `app` project

![image](https://user-images.githubusercontent.com/1567498/34628222-e9ab1ba6-f263-11e7-8b32-ff0222a64535.png)

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
