### ISSUE TITLE
Local query and mutation cache

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#468]
I'm wondering where the local operation cache is located, for both the Electron app and the express middleware.

I'm working with different projects that are all running on `localhost:4000`, and everytime I start a new project and I open the electron app, it gets seeded with tabs that contain queries and mutations that are invalid for my current project. Instead, I would like the queries saved _per project_, rather than _per URL_.

Also, is there a way to fully reset the query and mutation cache?

**Comment by timsuchanek** [comment]
The cache is located in localStorage.
We fixed the playground to take the path of the project as the key for the state.
This should fix the described scenario!
Please reopen if you have more questions / it's not fixed for you.
