### ISSUE TITLE
Black screen with 1.3.23 and 1.3.24 after url entered

### ISSUE THREAD

**Issue by tobkle** [prismagraphql/graphql-playground#491]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra 10.13.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

With 1.3.20 it is still working. 
With 1.3.23, 1.3.24 it doesn't work any more.

( In addition: If I had installed 1.3.24, it installs 1.3.23 as an update. I suppose this shouldn't be like that. )

#### What is the expected behavior?

Not seeing a black screen after entering the graphql url.

#### What is the actual behavior?

After entering the url and pressing return key, the screen gets black. Nothing happens any more. If I switch on the debugger tools, I can see the following errors in the console:
```
TypeError: Cannot read property 'attach' of undefined
    at Object.keyMap (app.b5da686….js:7683)
    at new CodeMirror$1 (app.b5da686….js:7844)
    at CodeMirror$1 (app.b5da686….js:7789)
    at QueryEditor.componentDidMount (app.b5da686….js:45963)
    at commitLifeCycles (app.b5da686….js:84123)
    at b (app.b5da686….js:84132)
    at m (app.b5da686….js:84143)
    at w (app.b5da686….js:84142)
    at batchedUpdates (app.b5da686….js:84145)
    at tc (app.b5da686….js:84028)
    at vd (app.b5da686….js:84045)

TypeError: Cannot read property 'attach' of undefined
    at Object.keyMap (app.b5da686….js:7683)
    at new CodeMirror$1 (app.b5da686….js:7844)
    at CodeMirror$1 (app.b5da686….js:7789)
    at QueryEditor.componentDidMount (app.b5da686….js:45963)
    at commitLifeCycles (app.b5da686….js:84123)
    at b (app.b5da686….js:84132)
    at m (app.b5da686….js:84143)
    at w (app.b5da686….js:84142)
    at batchedUpdates (app.b5da686….js:84145)
    at tc (app.b5da686….js:84028)
    at vd (app.b5da686….js:84045)

app.b5da686….js:116032 WebSocket connection to 'wss://graphcool.aws-xxxxxx.xxx' failed: Error during WebSocket handshake: Unexpected response code: 200
```
(removed the real server wss:// url here, because I don't want to show it publicly. If you would like to connect to the server I can send you the url in another way.)

The second console error with property attach is showing an error here:
```
  option("theme", "default", function (cm) {
    themeChanged(cm);
    guttersChanged(cm);
  }, true);
  option("keyMap", "default", function (cm, val, old) {
    var next = getKeyMap(val);
    var prev = old != Init && getKeyMap(old);
    if (prev && prev.detach) { prev.detach(cm, next); }
    HERE: ==> if (next.attach) { next.attach(cm, prev || null); }
```
Maybe this helps. The other location is in an uglified location.

My backend does (hopefully) work, as Postman delivers correct responses. It is behind a traefik.io proxy.

**Comment by jvbianchi** [comment]
Versions 1.4.1 and 1.4.2 are also affected by this

**Comment by timsuchanek** [comment]
Thanks for reporting @tobkle! Can you try the latest electron app (1.4.3)? That has probably fixed this problem.

**Comment by kazimanzurrashid** [comment]
Still encountering the same, Version 1.4.5 (1.4.5.2716)

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
