### ISSUE TITLE
Keyboard shortcuts don't work on windows

### ISSUE THREAD

**Issue by fabien0102** [prismagraphql/graphql-playground#513]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.4.0

#### What is the expected behavior?
Have all keyboard shortcuts available on windows with `Ctrl` instead of `Cmd`

#### What is the actual behavior?
![image](https://user-images.githubusercontent.com/1761469/35142571-f8dd91c6-fcfe-11e7-9052-ed8b2fbdc065.png)

#### What steps may we take to reproduce the behavior?
Install the 1.4.0 version on windows and try to do any shortcut

BTW, I don't see any shortcut for **Prettify** 😞 (I suggest `Shift+Alt+F` as VScode 😄 )

**Comment by fabien0102** [comment]
I have find this for Prettify:

```js
'Shift-Ctrl-P': () => {
          if (this.props.onPrettifyQuery) {
            this.props.onPrettifyQuery()
          }
        },
```
But it does'nt work too

**Comment by fabien0102** [comment]
It's a really quick fix to do just replace `Cmd` to `CmdOrCtrl` but I can't execute the project locally…

![image](https://user-images.githubusercontent.com/1761469/35143804-ea1aa562-fd02-11e7-9437-265a421d46bf.png)

(I'm up to date with `master` and I have already do a fresh install of dependencies with yarn)

Is it normal? ^^

**Comment by timsuchanek** [comment]
Hey @fabien0102 no that is not normal! So right now the only environments that I can help you with are Mac & Linux, both are working right now, you can see in Circle that the build is successful.
https://circleci.com/gh/graphcool/graphql-playground

So I guess it's a windows issue :/
We recently updated a lot of dependencies, it sounds like the css-loader is not working correctly on windows.
The only ideas that I have are: Check if you have the latest `node` & from the recently updated dependencies css-loader & style-loader: Check if an older version fixes this
