### ISSUE TITLE
Rename Tabs

### ISSUE THREAD

**Issue by philcockfield** [prismagraphql/graphql-playground#533]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground

### Feature Request

It would be good to be able to edit the display names of tabs.

![image](https://user-images.githubusercontent.com/185555/35358086-5c5ff8b4-01ba-11e8-8c36-99f8571e5fc1.png)

An obvious interaction would be to double click the tab name, and have the label become editable.

**Comment by Weakky** [comment]
This issue should probably be closed right ?

**Comment by timsuchanek** [comment]
@Weakky indeed!
