### ISSUE TITLE
Security Consideration: subscriptions.graphql.cool 

### ISSUE THREAD

**Issue by johannestroeger** [prismagraphql/graphql-playground#535]
Hey, 

i am using `GraphQL Playground HTML` in version 1.2.0 (absinthe/graphql-playground). I was wondering why the playground is connecting (by default) to a websocket at **wss://subscriptions.graph.cool**. Could you please explain why this is necessary?

![screenshot_playground](https://user-images.githubusercontent.com/21410/35403777-19d1f73a-0201-11e8-9ca2-17e8f4399393.png)

//cc @benwilson512

**Comment by beardedeagle** [comment]
inquiring minds want to know

**Comment by timsuchanek** [comment]
@johannestroeger My apologies for that weird behavior in the playground. That endpoint you can see there was used for testing, if a websocket endpoint is valid. I just removed it and replaced it with the correct value (which is the `subscriptionsEndpoint`), it will be released today or tomorrow.

**Comment by benwilson512** [comment]
Excellent, glad to hear it!

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
