### ISSUE TITLE
Playground crashes on schema exploration

### ISSUE THREAD

**Issue by adamjking3** [prismagraphql/graphql-playground#572]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OSX 10.13.3

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Electron 1.4.3.2587

#### What is the expected behavior?
Viewing a specific query in the Schema explorer shows the queries attributes.

#### What is the actual behavior?
Viewing a specific query in the Schema explorer crashes the playground.

#### What steps may we take to reproduce the behavior?
I haven't found a way to reproduce/fix it yet, although this is the output to the console when I click the offending query in the schema explorer.

_Please provide a gif or image of the issue for a quicker response/fix._

![screen shot 2018-02-15 at 5 37 34 pm](https://user-images.githubusercontent.com/14098106/36288253-f6b11124-1276-11e8-9a89-c19b40f795f0.png)

**Comment by seivan** [comment]
This should be fixed in `1.5.2`

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
