### ISSUE TITLE
Can't run development guide

### ISSUE THREAD

**Issue by miguelrcDEV** [prismagraphql/graphql-playground#585]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [X] GraphQL Playground (REACT)
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Linux 16.04

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
React development guide

#### What is the expected behavior?
Launch GraphQL Playgraound react like development steps says.

#### What is the actual behavior?
I'm trying to run GraphQL Playground like says in https://github.com/graphcool/graphql-playground#development . But when I run these commands the next error is prompted: 
```
./node_modules/react-codemirror/node_modules/react-dom/lib/ReactNodeTypes.js
Module not found: Can't resolve 'react/lib/React' in '/home/miguel/Documentos/TESTS/graphql-playground/packages/graphql-playground-react/node_modules/react-codemirror/node_modules/react-dom/lib'
```
Am I doig something wrong? Any ideas? Thanks in advance

#### What steps may we take to reproduce the behavior?
Clone project and run development steps: https://github.com/graphcool/graphql-playground#development

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by rmosolgo** [comment]
I had a similar problem, I cloned and ran: 

```
$ yarn 
$ cd packages/graphql-playground-react
$ yarn start
```

And it raised an error about missing the package `chalk` (Sorry, I don't have the full error, my terminal history is gone!). 

But I ran `$ yarn install` in the local directory (`packages/graphql-playground-react`), then the development server booted. 

(However, it wasn't the end of my issues, now loading the page gives a different error: 

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/2231765/36864624-3439b7d2-1d5b-11e8-868c-dac5ac232f47.png">

)

**Comment by timsuchanek** [comment]
Thanks for reporting! Which version of `node` and `yarn` are you using? With `node@8` and `yarn@1.6.0` it's working for us on mac and linux in circleci.

**Comment by rmosolgo** [comment]
Sorry, I'm not working on this project anymore, so I can't really answer :'( feel free to close this if it's inactive. (I can't close it since I didn't open it).

**Comment by timsuchanek** [comment]
Thanks, I closed this for now.
