### ISSUE TITLE
Opening playground from terminal doesn't work after upgrade

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#589]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

MacOS Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

This happens with every version, for example `1.4.3` and `1.4.4`.

#### What is the expected behavior?

After downloading the latest `.dmg` and installing it, I can open the Playground using `prisma playground` or `graphql playground` right away.

#### What is the actual behavior?

After downloading the latest `.dmg` and installing it, running `prisma playground` or `graphql playground` doesn't result in anything.

#### What steps may we take to reproduce the behavior?

Install an earlier version. Download the latest `.dmg`. Install it and open the Playground app for the first time. Close it. From your terminal, run `prisma init`, then `prisma playground`. Nothing happens.
 
_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by marktani** [comment]
Workaround:

* Manually open the Electron App so the starting screen with recent projects comes up.
* run `prisma playground` or `graphql playround`. This opens the project in the already opened app.

From now on, it works as expected again.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
