### ISSUE TITLE
Path to GraphQL endpoint ignored

### ISSUE THREAD

**Issue by nikcorg** [prismagraphql/graphql-playground#592]
GraphQL playground is ignoring the path part of the URL to the GraphQL endpoint.

- I have my GraphQL server responding on `POST` requests to `localhost:5152/graph`. 
- GraphQL Playground insists on sending its requests to `/`.
- Copy curl copies the command with the correct path  
  (`curl 'http://localhost:5152/graph/' [...rest omitted as noise, assume it works]`)

This is probably a regression, because this only started happening after accepting the most recent update. Unfortunately, I don't know what version the previous installed version was, but it was at least a month old.

#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

OS X 10.12.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.4.4.2771

#### What is the expected behavior?

The query is posted to the URL in the location bar.

#### What is the actual behavior?

The query is posted the host in the location bar, disregarding the path.

#### What steps may we take to reproduce the behavior?

![graphql_playground_and_1__node](https://user-images.githubusercontent.com/816988/37048506-f9e406be-2165-11e8-9d97-5db112395c8f.png)

**Comment by G3z** [comment]
I noticed that if you set the url in the address bar it's ignored ( but if you set it correctly when you open GQLP it works

**Comment by nikcorg** [comment]
You're right. If I fill in the URL the behaviour doesn't repeat. If I reopen the same using an item in the list of __Recent__ sessions, the behaviour is as described in the original issue.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
