### ISSUE TITLE
Feature request: Change font

### ISSUE THREAD

**Issue by blackxored** [prismagraphql/graphql-playground#593]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

MacOS High Sierra though not relevant.

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

Latest.

#### What is the expected behavior?

I want to be able to change the font that's used in the editor and (ideally) the response as well.
What can I say? I love Fira Code.

#### What is the actual behavior?

Fonts are fixed to Open Sans and Source Code Pro iirc.

#### What steps may we take to reproduce the behavior?

There aren't any, new feature request. In addition an rc file for the electron app would be great as well.

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by Huvik** [comment]
There is already pull request for it #492

**Comment by Huvik** [comment]
Font its possible to change trought config :)
