### ISSUE TITLE
Playground cuts off `path` of URL when used in browser 

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/graphql-playground#598]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [x] GraphQL Playground Express Middleware (Yoga)
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What is the expected behavior?

The URL in the browser bar should be identical to the URL that's used by the Playground to access the GraphQL API. 

#### What is the actual behavior?

If the URL has a _path_ in the end (e.g. `https://rkx8et8x7g.execute-api.eu-west-1.amazonaws.com/staging/`), this should be the considered the URL of the GraphQL API the Playground should interact with.

#### What steps may we take to reproduce the behavior?

Deploy a GraphQL Yoga server with `up`, like in [this](https://blog.graph.cool/one-click-graphql-server-deployment-with-apex-up-522f2b75a2ac) tutorial

_Please provide a gif or image of the issue for a quicker response/fix._

![image](https://user-images.githubusercontent.com/4058327/37337845-cd9e9e20-26b5-11e8-88b4-745311cd464f.png)

**Comment by muhajirframe** [comment]
any update?

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
