### ISSUE TITLE
Add ability to show raw response

### ISSUE THREAD

**Issue by hailwood** [prismagraphql/graphql-playground#606]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What is the expected behavior?
Ability to see the raw response returned if it's invalid json.
Ideally we could open this response in our default browser or a webview.

#### What is the actual behavior?
```
FetchError: invalid json response body at http://example.com/graphql reason: Unexpected token < in JSON at position 0
    at file:///opt/GraphQL%20Playground/resources/app.asar/lib/dist/app.e6cccecae5fb4fab8eb9.js:52537:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

#### What steps may we take to reproduce the behavior?
Send a valid request that returns an invalid response

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
