### ISSUE TITLE
UI Crash when switching environments

### ISSUE THREAD

**Issue by blackxored** [prismagraphql/graphql-playground#607]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

macOS 10.13.3

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.4.5.2716

#### What is the expected behavior?

To load workspace.

#### What is the actual behavior?

A blank screen.

#### What steps may we take to reproduce the behavior?

I've two envs on `.graphqlconfig`. When switching to my `prod` environment I can see the normal UI from a moment but then it goes to a gray screen. Something related to loading my schema as if I point it out to a non-existent schema it loads correctly.

![](https://www.dropbox.com/s/u717c1p5yrvqoyz/Screenshot%202018-03-26%2013.02.19.png?dl=1)

As you can see, it looks like a full-blown crash.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
