### ISSUE TITLE
The playground "forgot" my recent queries and mutations.

### ISSUE THREAD

**Issue by MichelDiz** [prismagraphql/graphql-playground#633]
#### What OS and OS version are you experiencing the issue(s) on?
Mac Os HighSierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Last update

#### What is the expected behavior?
Never forget my recent queries and mutations.

#### What is the actual behavior?

For some reason, after two consecutive updates (I did not understand why). The playground "forgot" my recent queries and mutations.

#### What steps may we take to reproduce the behavior?

It was random, one moment I was working and asked to update. I did. Then 2 hours later asked again. And I did. Then he "cleaned" everything.

**Comment by jhliberty** [comment]
Had the same issue occur for me. Lost a bit of work.

**Comment by Huvik** [comment]
Read release notes https://github.com/graphcool/graphql-playground/releases/tag/v1.5.0

**Comment by MichelDiz** [comment]
Well, again today, seven days after that. The same issue occurred again ...

the Playground, warned that there was an update. And I have no choice but to say "later" all the time. I lost everything again.

I'm using a Brew installation, by the way.

And you see, Graphql PG requested the update twice with an average difference of two hours (not sure, but it was a long time difference time).

This behavior makes no sense. Should not this be a separate data file from the installation file?

Please reopen this issue as the problem persists. Downgrade is irrelevant if you need to maintain the application update policy. If updating is irrelevant so there should be a "never update" option.

**Comment by Huvik** [comment]
Its because there were release of `1.5.3` and `1.5.4`, do you using workspaces?

**Comment by MichelDiz** [comment]
@Huvik Yes, I do. I have a GraphQL HTTP endpoint in a virtual machine with Docker. And Always create few Tabs with some test contexts. When the update happen only shows the "Movie db, Instagram and Pokemon" examples.

**Comment by Huvik** [comment]
Do you use `.graphqlconfig`?

**Comment by MichelDiz** [comment]
No, what's about .graphqlconfig? I can save queries, mutations and subs templates creating a .graphqlconfig? or is about that repo https://github.com/graphcool/graphql-config ?

**Comment by timsuchanek** [comment]
We're sorry about the inconveniences @MichelDiz! This very likely happened due to a change of the inner data structure of the Playground.
I'm closing this now due to inactivity. This will not happen in the future anymore. The latest Playground should save the state as expected.

**Comment by deejayxd07** [comment]
I'm still experiencing this issue, help!

**Comment by deejayxd07** [comment]
I'm currently experiencing this issue on v 1.6.2, is there a workaround for this? Thanks
