### ISSUE TITLE
Endpoint and WebSocket url

### ISSUE THREAD

**Issue by Fi1osof** [prismagraphql/graphql-playground#635]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground HTML

#### What OS and OS version are you experiencing the issue(s) on?
Ubuntu 17
Google Chrome 65.0.3325.181

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.4.3

#### What steps may we take to reproduce the behavior?
Details here: https://github.com/graphcool/prisma/issues/1989#issuecomment-378795096

**Comment by Fi1osof** [comment]
After upgrade prisma@1.6.3 and playground@1.5.13 broken completely for relative url.
![_079](https://user-images.githubusercontent.com/2550668/39110030-351a530e-46d8-11e8-93a9-b681d01985d0.jpg)

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!

**Comment by Fi1osof** [comment]
@timsuchanek thanks!
