### ISSUE TITLE
No WS connection is initialized

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#645]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS X Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

`1.5.4`.

#### What is the expected behavior?

Opening a project opens a WS connection to the subscription endpoint.

#### What is the actual behavior?

No WS connection is opened.

#### What steps may we take to reproduce the behavior?

```sh
prisma init test
cd test
prisma deploy
prisma playground
```

Press CMD+Shift+I. Press CMD+R. Note that no WS connection has been created:

![image](https://user-images.githubusercontent.com/1780597/38813841-5961e9b8-4190-11e8-97ad-aa486dbe190b.png)

**Comment by timsuchanek** [comment]
This is correct, we're initializing connections lazy to prevent unnecessary traffic.
