### ISSUE TITLE
Light theme breaks Prisma Playground

### ISSUE THREAD

**Issue by nikolasburk** [prismagraphql/graphql-playground#649]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS Sierra 10.12.6 (16G29)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

Version 1.5.4 (1.5.4)

#### What is the expected behavior?

Light theme should display response pane for database project.

#### What is the actual behavior?

It only shows the query editor but I can't see the responses:

![image](https://user-images.githubusercontent.com/4058327/38928156-31a64cf6-4308-11e8-8a7c-9148e4ab7782.png)

Tried the following:
- open new tab
- restart playground
- switch back to dark (where response pane is visible again) and back to light

None of these helped.

App layer looks ok:

![image](https://user-images.githubusercontent.com/4058327/38928218-6528833c-4308-11e8-8aaf-3cf97a2ad470.png)

**Comment by Huvik** [comment]
Its fixed in new version
