### ISSUE TITLE
Try to show response even if status code is 400

### ISSUE THREAD

**Issue by novemberborn** [prismagraphql/graphql-playground#652]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

macOS 10.13.4

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

v1.5.4

#### What is the expected behavior?

[`apollo-server-core`](https://github.com/apollographql/apollo-server/blob/5bebbf12b14714901ec4ecc49244c1290b8c0e56/packages/apollo-server-core/src/runHttpQuery.ts#L182) responds with a `400` status code if there are errors in the request as received from the client. Playground doesn't show the server response, instead it prints:

```json
{
  "error": "Response not successful: Received status code 400"
}
```

#### What is the actual behavior?

When it receives a response with a `400` status code, Playground ensures the response is still JSON and parses it. If it has GraphQL errors it prints them.

#### What steps may we take to reproduce the behavior?

Submit an invalid client request to a GraphQL server based on Apollo, e.g. pass an array variable where a string is expected.

**Comment by Fi1osof** [comment]
Got same problem after upgrade prisma (older versions works fine). This error when use graphql-yoga via yarn start and graphql playground both.
Playground version 1.5.13

**Comment by ojongerius** [comment]
We are using GraphQL Playground Lambda Middleware and see this behaviour in 1.5.x. 1.4.x and older work fine.

A very simple type that has a mandatory argument called like so:

```graphql
query{ getUser {
  name
}}
```

In 1.4.x:

```graphql
{
  "errors": [
    {
      "message": "Field \"getUser\" argument \"email\" of type \"String!\" is required but not provided.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

In 1.5x:

```graphql
{
  "error": "Response not successful: Received status code 400"
}
```
