### ISSUE TITLE
Cookies are not sent

### ISSUE THREAD

**Issue by michalkvasnicak** [prismagraphql/graphql-playground#656]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

`1.6.1`

#### What is the expected behavior?

When I set `request.credentials: include` in settings, cookies should be sent

#### What is the actual behavior?

Cookies are not sent.

When I downgrade to `graphql-playground-middleware-express@1.4.9` everything works just fine.

**Comment by reflog** [comment]
same here. the latest version doesn't send cookies, settings are ignored. 1.4.9 works fine.

**Comment by capaj** [comment]
I am using graphql-playground-middleware-koa and I have the same issue. @michalkvasnicak how do you pass the `request.credentials: include` settings to the middleware?
Also wouldn't it make sense to send all cookies by default?

**Comment by michalkvasnicak** [comment]
@capaj the middleware is responsible for rendering GraphQL Playground, so I just set `request.credentials` to `include` in the settings of GraphQL Playground (in browser).

**Comment by rocknrolla777** [comment]
@michalkvasnicak it didn't help. Request doesn't include cookies.

**Comment by michalkvasnicak** [comment]
@rocknrolla777 yeah I know, I just answered the question of @capaj. We need to wait until the new version is released.

**Comment by 10thfloor** [comment]
The problem still exists with latest `graphql-playground-middleware-express`. 
I can confirm that downgrading this package to 1.4.9 fixes things.

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!

**Comment by ivan-kleshnin** [comment]
Tested 1.7.2 in different browsers. Cookies **are not** sent 😞

**Comment by ivan-kleshnin** [comment]
`npm install graphql-playground-html@latest` -> 1.6.13
`npm install graphql-playground@latest` -> 1.3.17

The latest `graphql-playground` here at GitHub is 1.8.10

Which version is the latest? 1.8.10? Why NPM is so much older?
No idea what's going on here 😨

**Comment by maxwellsmart84** [comment]
👍 I have same issue - setting a "Cookie" in the header and the request.credentials to "include" does not send the cookie

**Comment by yoshiakis** [comment]
Hi @maxwellsmart84, did you use `Set-Cookie` header to set cookie?

**Comment by maxwellsmart84** [comment]
@yoshiakis   I have my settings like so:
<img width="327" alt="Screen Shot 2019-06-05 at 7 18 36 PM" src="https://user-images.githubusercontent.com/14876902/59204868-92152200-8b6f-11e9-9a7c-0e378c66a77b.png">
<img width="1036" alt="Screen Shot 2019-06-05 at 7 18 42 PM" src="https://user-images.githubusercontent.com/14876902/59204872-93464f00-8b6f-11e9-833e-7b32d52da942.png">


Am I missing a setting?

**Comment by yoshiakis** [comment]
@maxwellsmart84 You can't set cookie from the HTTP HEADERS panel. You need to receive `Set-Cookie` header from a server in advance to set cookie.
