### ISSUE TITLE
Playground (v1.5.6) application goes blank in Windows 10 pro

### ISSUE THREAD

**Issue by ajit555** [prismagraphql/graphql-playground#659]
#### This issue pertains to the following package(s):

- [* ] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10 pro 64-bit (version 1803)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-electron-setup-1.5.6.exe

#### What is the expected behavior?
Installed for the first time. 
Selected online movie database URL, the query window opened successfully. 

After that, I clicked on some history link (i do not remember and can not reproduce as not able to use the app thereafter) and the screen went blank, with only Navigation on top. Can not go to the query screen again. Clicking any item in the navigation, the below screen remains blank. I closed and opened the app again, selected movie database url again, the blank screen with navigation appears. 

After application re-installation also (used Wise uninstaller to remove any residual config files), the same blank screen appears with navigation, making application impossible to use.

The screencapture gif is attached.

#### What is the actual behavior?
See above detail

#### What steps may we take to reproduce the behavior?
See above detail

#### Please provide a gif or image of the issue for a quicker response/fix._
![graphql-playground-electron-1 5 6-windows10-issue](https://user-images.githubusercontent.com/194380/39669335-9634d21c-5106-11e8-91e1-405d76c77400.gif)

**Comment by Huvik** [comment]
Can you please provide console output from developer tools?

**Comment by ajit555** [comment]
Console output from developer tools:

![error](https://user-images.githubusercontent.com/194380/39683008-bbad1bd8-51d0-11e8-90c1-6eef5dfde34d.jpg)
[-1525661829494.log](https://github.com/graphcool/graphql-playground/files/1978387/-1525661829494.log)
[-1525661852125.log](https://github.com/graphcool/graphql-playground/files/1978388/-1525661852125.log)

**Comment by operolim** [comment]
@ajit555 I run into that same issue on my mac. Clearing my local storage cache fixed it for me. You could try that as a workaround for now, until this bug is fixed.

**Comment by ajit555** [comment]
@operolim I would try that and reply if it fixed. Sorry for late reply as got busy in other work.

**Comment by jpwilliams** [comment]
I had the same issue on Mac with v1.5.6, though seems fixed in v1.5.8. Can anyone else confirm?

**Comment by ajit555** [comment]
Yes, the issue is fixed on Windows 10 after installing  v1.5.8 (graphql-playground-electron-setup-1.5.8.exe).

However, in application>settings, it is showing version as "1.6.6"

**Comment by Huvik** [comment]
@ajit555 You can read more about it https://github.com/prismagraphql/graphql-playground/issues/662

**Comment by timsuchanek** [comment]
It seems that this is fixed in the latest version. Please let me know if this is still a problem for you, then we reopen this issue.
