### ISSUE TITLE
Fetch `credentials: include` has been reverted since moving to Apollo Client HttpLink in graphql-playground-react

### ISSUE THREAD

**Issue by DanlanNZ** [prismagraphql/graphql-playground#664]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
"graphql-playground-middleware-express": "^1.6.1",

#### What is the expected behavior?
session cookies included with requests

#### What is the actual behavior?
cookies not sent

#### What steps may we take to reproduce the behavior?
use a GQL API that requires session cookies

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by DanlanNZ** [comment]
just realised this is a duplicate of #656

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
