### ISSUE TITLE
Cannot use graphql-playground App

### ISSUE THREAD

**Issue by o3o3o** [prismagraphql/graphql-playground#675]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
 

#### What OS and OS version are you experiencing the issue(s) on?
mac os 10.12.6 (16G1212)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
GraphQL Playground 1.5.6

###

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

The App is blocking when I input the url. And I am sure the url is ok with Graphiql client.

```
var selectedItem = this.props.items.get(this.state.selectedItemIndex).toJS();

: 
app.ad6d65d….js:172971 Uncaught TypeError: Cannot read property 'toJS' of undefined
    at HistoryPopup.render (app.ad6d65d….js:172971)
    at h (app.ad6d65d….js:124842)
    at beginWork (app.ad6d65d….js:124845)
    at d (app.ad6d65d….js:124873)
    at f (app.ad6d65d….js:124873)
    at g (app.ad6d65d….js:124874)
    at m (app.ad6d65d….js:124881)
    at w (app.ad6d65d….js:124880)
    at batchedUpdates (app.ad6d65d….js:124883)
    at tc (app.ad6d65d….js:124766)
    at vd (app.ad6d65d….js:124783)
```

![graphql_playground_bug](https://user-images.githubusercontent.com/4308542/39847257-2fc67762-5433-11e8-851d-68d3907b0420.gif)

**Comment by Kacppian** [comment]
This doesn't happen anymore in GraphQL Playground 1.7.0. Can you update your client and check if it's still happening?

**Comment by timsuchanek** [comment]
Fixed in the latest version. Please let us know if you still have that issue, then we reopen it!
