### ISSUE TITLE
Electron App: Is there a way to include credentials for secured graphql endpoints?

### ISSUE THREAD

**Issue by blevine** [prismagraphql/graphql-playground#680]
Any way to include credentials (preferably for BASIC auth) using the Electron App?

**Comment by timsuchanek** [comment]
You can indeed set headers!
![image](https://user-images.githubusercontent.com/1094804/40661150-5164fa36-6353-11e8-97c0-f527bc19d9d9.png)

You can read more about how to put basic auth into the headers here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication
