### ISSUE TITLE
Documentation for Playground Settings?

### ISSUE THREAD

**Issue by robbyemmert** [prismagraphql/graphql-playground#684]
#### This issue pertains to the following package(s):

- [x ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS 10.13.4

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.5.7

#### What is the expected behavior?
I should be able to find documentation in human readable format listing available settings, and available values for those settings, ideally with a few examples. There should be a prominent link to this documentation from the readme.

If those settings happen to include an option for setting editor indentation, you get an extra cookie.
If there is autocomplete in the settings view, like VS Code has, or better yet a GUI, then you get an extra box of cookies.

#### What is the actual behavior?
I can't find any documentation for what settings are available, or what effects I can expect from the available options. The most helpful thread regarding settings that I found was closed with a reference to download [Insomnia](https://insomnia.rest/), another REST/GraphQL client with more features. #359 

If I open the settings view itself, all I see is an editable JSON object with a few defaults, most of which I have no idea what they do:
```
{
  "general.betaUpdates": false,
  "editor.theme": "dark",
  "editor.reuseHeaders": true,
  "request.credentials": "omit",
  "tracing.hideTracingResponse": true
}
```
The result is that I am frustrated at not being able to customize GraphQL Playground and find myself investigating Insomnia as a replacement.

#### What steps may we take to reproduce the behavior?
Look at the readme. Google "GraphQL Playground Settings". If you find anything helpful regarding settings & options, please tell me!

_Please provide a gif or image of the issue for a quicker response/fix._

<img width="1280" alt="screen shot 2018-05-16 at 10 35 29 am" src="https://user-images.githubusercontent.com/7490085/40093501-152c752a-58f5-11e8-9219-58eed2bf6319.png">

**Comment by timsuchanek** [comment]
Thanks for raising this issue!
We added very basic docs around this issue: https://github.com/prismagraphql/graphql-playground/blob/master/README.md#settings

Feel free to do a PR to enhance them :)

**Comment by jonaskello** [comment]
I'm wondering what the `reuseHeaders` setting does, I can see that it exists but find no explanation of what it does....

**Comment by Huvik** [comment]
@jonaskello I just added a note in README, it just copy headers from last opened tab if you create new one.

**Comment by jonaskello** [comment]
@Huvik Thanks :-)
