### ISSUE TITLE
File explorer

### ISSUE THREAD

**Issue by otissv** [prismagraphql/graphql-playground#69]
Changed
Added files FileExplorerView to ElectronApp.tsx and events

Added
- reducersfiles.ts/ and actions/files.ts for files
- FileExplorerView/FileExplorerView.tsx file tree component
- dirToJson.js creates json tree from project folder structure
- files.js contains backend events
get-file-data = loads file content when opened via os
get-file-tree = creates json directory
load-file-content = loads file content
save-file = saves file
delete-file = deletes file
create-folder = create folder
delete-folder = deletes folder
move-folder = moves folder

- ipEvents.js contains frontend events
file-tree-changed receives file structure
file-saved = receives file save response
content-loaded = receives file content

TODO:
- Need to add location to files tree and update tree/directory structure on changes
- UI for file editor
- Icons for open and collapsed folders
- Add function to only have included globs from .graphqlconfig in
 dirToJoson.js.

**Comment by timsuchanek** [comment]
Closing this, as it is not planned to be implemented for the foreseeable future.
