### ISSUE TITLE
UI issue for Light theme when using subscription

### ISSUE THREAD

**Issue by playerx** [prismagraphql/graphql-playground#711]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macOS High Sierra (Version 10.13.4)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Version 1.5.9 (1.5.9)

#### What is the expected behavior?
to have light theme everywhere

#### What is the actual behavior?
there is dark theme "Listening...", as I guess something is hard coded here :) 

#### What steps may we take to reproduce the behavior?
subscribe any subscription

_Please provide a gif or image of the issue for a quicker response/fix._
<img width="1059" alt="screen shot 2018-05-29 at 12 00 37" src="https://user-images.githubusercontent.com/1698274/40645701-2f84e158-6338-11e8-9ad0-517191d75afb.png">

**Comment by Huvik** [comment]
This will be fixed in #641

**Comment by playerx** [comment]
cool thanks 👍

**Comment by Huvik** [comment]
Keep it open i will close it latter :)

**Comment by Huvik** [comment]
Its fixed in 1.6.0
