### ISSUE TITLE
Playground seems broken on Safari

### ISSUE THREAD

**Issue by do4gr** [prismagraphql/graphql-playground#716]
- [x] GraphQL Playground HTML

#### What OS and OS version are you experiencing the issue(s) on?
Mac Os, Safari

<img width="1395" alt="bildschirmfoto 2018-06-01 um 10 20 54" src="https://user-images.githubusercontent.com/16278407/40830158-e72a2b66-6585-11e8-9938-406489237124.png">

**Comment by Huvik** [comment]
I was trying the latest version of the playground on safari but I can't reproduce it. If its still problem reopen.
