### ISSUE TITLE
Adjust prettier print width based on editor width

### ISSUE THREAD

**Issue by schickling** [prismagraphql/graphql-playground#721]
One of the nice features of prettier is that you're able to set the `--print-width` argument which is useful to influence the formatting based on the available width. We should leverage this feature and base it on the available editor width (but still cap at 80) to avoid situations like this one:

![image](https://user-images.githubusercontent.com/1567498/40901865-4759d812-67d2-11e8-8f29-2451bd551456.png)

See [Prettier Playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAFQE4E90wToDu2AlvOrhAK7boCONce6AFi3ADpTA-roAhgBthAMTLCAtgGcAFADNJ8bEnTB0AEzLY4YQtgD6UCDEMJNMw8Qps1XEAA9nDgDTowuwfE0BBMyZmZFBqUDSi6AC+AJTq-AIebILYgvosMnFQCQlkmvECkfGFUMUgriAQAA4wZNAyyKDJ2BDEAArJCPUoggBuELllIABGKWAA1nAwAMqVqcEA5sgw2MzlwTIsMK0p81KCyAoiG+UAVjKOAEKjE9OCUnAAMsFwB0dw5bPYG9jIIPMplTYDGEg0q5FgAHVcjA2MgAGwABg+zQ2EIBvzBcG+PRe5V0TB0cG2gl2+yQh2ExxAGykZCWK3e1IWwjgAEUaKYXuS3uUYIIhlDNDDkAAmXkpSQLADCECke1+JiguJANA2mH5XQpG0ikSAA)

**Comment by Huvik** [comment]
Ye, i encountered it too during weekend i will fix it :)

**Comment by schickling** [comment]
@Huvik @timsuchanek I'm not sure if #739 exactly implements the way how I originally imagined the feature/improvement. @Huvik is my understanding correct that with your latest PR I can set a specific value but it's not automatically adjusted based on the query editor width? (Maybe the current way is "good enough" but I thought it might be a nice UX improvement.)

**Comment by Huvik** [comment]
I think there is a problem with calculation width of text to implement exact `max-width` of query to number of characters

**Comment by Huvik** [comment]
There is a problem with calculation max width of the query, because every char can have a different width. So it wouldn't be so accurate anyway, because there would be needed some kind of reserve.
