### ISSUE TITLE
[graphql-playground-electron] beautify the scroll bar

### ISSUE THREAD

**Issue by Lizhooh** [prismagraphql/graphql-playground#726]
#### This issue pertains to the following package(s):

-  GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?

win7

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

v1.6.0

#### What is the expected behavior?

Win7's default scroll bar does not look good, I hope to beautify the scroll bar style.

**Comment by Lizhooh** [comment]
@Huvik Hi, 

1. The scroll bar is displayed when the contents of the container are not full, and the display is inconsistent. You can use `overflow-y: auto` to fix.

![20180607204347](https://user-images.githubusercontent.com/19299088/41101093-c05663c8-6a95-11e8-86a3-6330beddaa07.png)


2. On the **`right`** is the effect of opening the `developer tools` to try to beautify the scroll bar.(use [::-webkit-scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar))

![20180607205121](https://user-images.githubusercontent.com/19299088/41101111-cde6e8fa-6a95-11e8-9531-1edb56f38308.png)

**Comment by Huvik** [comment]
@Lizhooh Can you make please PR for it? :) It would help a lot <3

**Comment by Lizhooh** [comment]
@Huvik I try to submit a PR for this, please wait.

**Comment by corstian** [comment]
While you're at it, did you take a look at the horizontal scrollbar for the tabs? That's a real monstrosity ;)

![image](https://user-images.githubusercontent.com/5021647/42291869-cc21177c-7fce-11e8-9a1b-45f79ff26d3f.png)
