### ISSUE TITLE
Double or triple clicking on hovered word in query has no effect

### ISSUE THREAD

**Issue by marktani** [prismagraphql/graphql-playground#768]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground HTML

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

The one exposed with Prisma `1.10.2`.

#### What is the expected behavior?

Double-clicking on a word in a query selects the word.
Triple-clicking on a word in a query selects the whole line.

#### What is the actual behavior?

When hovering a word, and it gets underlined (love that new feature btw!), double or triple clicking is ignored. Also see screenshot for the state I am talking about, In the screenshot, `where` is currently being hovered.

#### What steps may we take to reproduce the behavior?

![image](https://user-images.githubusercontent.com/1780597/42388784-f569a7ba-8146-11e8-9a4b-bba9060906ff.png)

**Comment by Huvik** [comment]
There are two modes in editor:

1. Normal mode where you can do everything double, tripple clicking. This is editing mode for general workflow.
2. Jump mode where you can click on definition and you jump to documentation. This mode is used for fast movement to types in docs. 

Between this two modes you can switch by holding `CMD` button. While holding `CMD` button you are in `JUMP` mode.
