### ISSUE TITLE
Support for connectionParams

### ISSUE THREAD

**Issue by makmm** [prismagraphql/graphql-playground#770]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

Is it possible to support `connectionParams` from Apollo?

**Comment by azz** [comment]
An extra panel in the bottom left (alongside `HTTP Headers` and `Query Parameters`) would be fantastic.

**Comment by azz** [comment]
I started working on this, but eventually realised that the `HTTP Headers` content is also sent as `connectionParams`.

https://github.com/prismagraphql/graphql-playground/blob/e1f715988099b74f7ea0ec19d612d97cfbf05848/packages/graphql-playground-react/src/state/sessions/fetchingSagas.ts#L66-L68

**Comment by azz** [comment]
Got a working implementation in the above commit. Only really needed if you want to have separate HTTP headers and `connectionParams`.

![image](https://user-images.githubusercontent.com/1297597/43992619-6af90ae0-9dc4-11e8-8a19-98d7dc53df70.png)

**Comment by makmm** [comment]
oh
