### ISSUE TITLE
Invalid queries get removed when trying to prettify them

### ISSUE THREAD

**Issue by do4gr** [prismagraphql/graphql-playground#773]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOs

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Safari and Chrome Web version

When trying to prettify an invalid query the code gets deleted. It should just not be formatted if it is invalid.

**Comment by carstenbaumhoegger** [comment]
I'm experiencing the same issue with the Electron App on macOS
